name: lambda_terraform.yaml

on:
  workflow_dispatch:
    inputs:
      lambda_name:
        description: 'Lambda Function Name'
        required: false

      s3_bucket:
        description: 'S3 bucket where Lambda deployment package is stored'
        required: false

      s3_key:
        description: 'Name of the Lambda deployment package in S3'
        required: false

      region:
        description: 'AWS region'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Assume AWS Role using OIDC
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::730335384723:role/backstage_interns_project
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ github.event.inputs.region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -var lambda_name=${{ github.event.inputs.lambda_name }} -var region=${{ github.event.inputs.region }} -var s3_bucket=${{ github.event.inputs.s3_bucket }} -var s3_key=${{ github.event.inputs.s3_key }} -auto-approve
